### ISSUE TITLE
DynamicServerListLoadBalancer ignores ping interval configuration

### ISSUE THREAD

**Issue by casidiablo** [Netflix/ribbon#200]
`DynamicServerListLoadBalancer` implementation of `setPing` [does not call][1] `super.setPing` which causes the load balancer to completely ignore the ping interval configuration. Is this intentional?

Everytime the server list is update it forces a ping on all servers, but what if I want to update that list only every 2 minutes but ping all servers every 15 seconds?

  [1]: https://github.com/Netflix/ribbon/blob/b4fd19bc62c2b09fea714627b5c8a1a1e8cbfec5/ribbon-loadbalancer/src/main/java/com/netflix/loadbalancer/DynamicServerListLoadBalancer.java#L216

**Comment by lasselasse** [comment]
Just ran into the same issue. I don't see any reason why DynamicServerListLoadBalancer overwrites setPing(), it could just be removed.

**Comment by lasselasse** [comment]
Are there any impediments to merging the fix for this issue, pull request #208?
We've had this much needed patch in production for months now and would love to see it included in the next release.
