### ISSUE TITLE
RoundRobinRule can only choose server MAX_INT times

### ISSUE THREAD

**Issue by maciej-kapusta** [Netflix/ribbon#259]
Hi, 

I noticed lately that you can only call RoundRobinRule MAX_INT times. This is due to the fact that you indefinitely increment AtomicInt nextIndexAi.
```
    index = nextIndexAI.incrementAndGet() % serverCount;
```
The index variable becomes negative, and no server is chosen. 

While you probably should do something like this:
```
    index = Math.abs(nextIndexAI.incrementAndGet()) % serverCount;
```
This normally is not a big deal, because we deploy often, but this time we reached the MAX_INT limit in 12 days, and we no longer could send any request.

Regards,

Maciej Kapusta

**Comment by drtechniko** [comment]
Hi Maciej,

I just merged a fix for this here: https://github.com/Netflix/ribbon/pull/260

I decided to make the int a long instead of the absolute value so that the modulo wraps around properly (assuming 10 servers) 7->8->9->0 instead of 7->8->7->6...

Best of luck!
