### ISSUE TITLE
Upgrade to jersey version to 1.20

### ISSUE THREAD

**Issue by spencergibb** [Netflix/ribbon#265]
In [gradle.properties](https://github.com/Netflix/ribbon/blob/33daee0f1582ec4580192f859ee2084bd715c99b/gradle.properties#L8)

Originally reported in [spring-cloud-netflix](https://github.com/spring-cloud/spring-cloud-netflix/issues/749#issuecomment-182969990) which referenced https://java.net/jira/browse/JERSEY-2795

**Comment by websusk** [comment]
Is there an option to use a load-heavy version of Ribbon using Spring Cloud Netflix before this is released?  Is is possible or recommended to override this dependency until them?

**Comment by PedroAlvarado** [comment]
@drtechniko @dmitry-cherkas The kind folks behind jersey released a new version [1.19.1](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.sun.jersey%22%20AND%20v%3A%221.19.1%22). This version includes a fix for[JERSEY-2795](https://java.net/jira/browse/JERSEY-2795) which a number of users are currently running into in production by proxy of using ribbon. I'd be great if you guys can help us get this dependency upgraded to address this issue. Thank you in advance for your help.

**Comment by drtechniko** [comment]
released. closing.
