### ISSUE TITLE
BestAvailableRule Can Be Improved

### ISSUE THREAD

**Issue by tkvangorder** [Netflix/ribbon#277]
The BestAvailableRule will route traffic to the first server with the smallest number of concurrent connections, even if that server is generating connection failures. This rule can be improved with a small change to the logic that will check for SuccessiveConnectionFailures when the number of concurrent requests is 0. This will make the rule favor those servers that have the lowest connection count and the lowest number of concurrent connection failures. This will help route traffic to healthy servers when other service nodes are heading towards an open circuit state.

``` java
    @Override
    public Server choose(Object key) {
        if (loadBalancerStats == null) {
            return super.choose(key);
        }
        List<Server> serverList = getLoadBalancer().getServerList(false);
        int minimalConcurrentConnections = Integer.MAX_VALUE;
        long currentTime = System.currentTimeMillis();
        Server chosen = null;
        for (Server server : serverList) {
            ServerStats serverStats = loadBalancerStats.getSingleServerStat(server);
            if (!serverStats.isCircuitBreakerTripped(currentTime)) {
                int concurrentConnections = serverStats.getActiveRequestsCount(currentTime);
                if (concurrentConnections == 0) {
                    // If there are not concurrent connections, lets see if
                    // there are any successive connection failures.
                    int errors = serverStats.getSuccessiveConnectionFailureCount();
                    if (errors > 0) {
                        // This will cause servers that have had a connection failure to be "less" favored than a server
                        // that is healthly
                        concurrentConnections = 1;
                    }
                }
                if (concurrentConnections < minimalConcurrentConnections) {
                    minimalConcurrentConnections = concurrentConnections;
                    chosen = server;
                }
            }
        }
        if (chosen == null) {
            return super.choose(key);
        } else {
            return chosen;
        }
    }
```

**Comment by d53dave** [comment]
That's a change my team would like to see as well. Determining the **best available** server should take failures into account.

**Comment by tkvangorder** [comment]
Fast-Forward two years, we had this custom rule in place and we ran into an issue! Once a box entered the error state and there was not enough load to choose it over one of the other "healthy" nodes, it would not reenter the pool! So I dont recommend this approach....maybe I should close this issue?
