### ISSUE TITLE
Ribbon properties not getting picked up with load balanced rest template and spring cloud

### ISSUE THREAD

**Issue by get2parag** [Netflix/ribbon#299]
I'm using ribbon in my project with spring cloud config for configurations and consul for service discovery. Have decorated my rest template with @LoadBalanced (spring cloud) annotation and using OkHttpClientRequestFactory as default request factory for the rest template with an ok http client.
I'm passing following ribbon properties 
<client-name>.ribbon.MaxAutoRetries=2
<client-name>.ribbon.MaxAutoRetriesNextServer=2
and few more like readTimeOut,connectTimeOut etc. via Archiaus but it seems these properties are not getting picked up as no request is getting retried after failure though request is going through RibbonLoadBalancerClient execute method.
Setup:-
I have two instances of service-1 running on my local and I'm accessing them via service-2. I would like if one of the instance of service-1 goes down and service-2 still makes a request to service-1 and if the call fails due to a connect refused exception ribbon should retry to the next server but currently that's not happening.

Please let me know I'm missing something or if you need any further information here.

**Comment by spencergibb** [comment]
This is not the right place for spring cloud issues.

**Comment by get2parag** [comment]
Moved this issue to spring-cloud-netflix project - [link](https://github.com/spring-cloud/spring-cloud-netflix/issues/1161)
