### ISSUE TITLE
Any update on status for gRPC enhancements for Netflix stack?

### ISSUE THREAD

**Issue by aameek** [Netflix/ribbon#306]
Is there an update on adding load balancing & discovery interceptors to gRPC like mentioned at https://github.com/Netflix/ribbon

"We currently contribute to the gRPC code base regularly. To help our teams migrate to a gRPC-based solution in production (and battle-test it), we are also adding load-balancing and discovery interceptors to achieve feature parity with the functionality Ribbon and Eureka provide. The interceptors are Netflix-internal at the moment. When we reach that level of confidence we hope to open-source this new approach. We don’t expect this to happen before Q3 of 2016."

**Comment by gfortaine** [comment]
cc @elandau

**Comment by imberda** [comment]
Is there any update on this? It would be great to see a gRPC (Java) load balancer implementation which uses Eureka for discovery. 

I'd strongly imagine there are a large number of projects / developers that are users of Eureka / Ribbon for REST. If the above were to be open sourced it would pave the way for those folks to easily adopt gRPC.

**Comment by maseb** [comment]
Bump. :)

**Comment by qiangdavidliu** [comment]
Hi. To give an update on this, our grpc specific interceptors are still internal at the moment. However, integration with current OSS eureka as a grpc NameResolver can be relatively straight forward and it looks like there has already been some provided by the community. For example,
- https://github.com/LogNet/grpc-spring-boot-starter
- https://github.com/ExampleDriven/grpc-eureka-java

(Please note that these are not what we use internally so please evaluate with your own needs in mind).
