### ISSUE TITLE
A vulnerability in jersey-apache-client4 

### ISSUE THREAD

**Issue by ammy1999** [Netflix/ribbon#356]
Hello,
Using spring-cloud-starter-ribbon version 2.0.0.M2 or 1.3.0.RELEASE,  I have a high vulnerability in jersey-apache-client4-1.19.1.jar ( when using dependency check ) , So I upgarde the version to 1.19.4 ,
`<dependency>
    <groupId>com.sun.jersey.contribs</groupId>
    <artifactId>jersey-apache-client4</artifactId>
    <version>1.19.4</version>
</dependency>`
 but nothing change, So, what can I do to remove this vulnerability

**Comment by spencergibb** [comment]
This is not the spring cloud netflix issue tracker.
