### ISSUE TITLE
Ribbon redirect failed on k8s

### ISSUE THREAD

**Issue by markhingston** [Netflix/ribbon#425]
Ribbon failed on redirecting request to the service instance on kubernetes platform.

![1952071809-5a137118d8680_articlex](https://user-images.githubusercontent.com/50924871/58196470-020a5800-7ce8-11e9-9ebc-c4127df0ac36.jpg)

**Comment by spencergibb** [comment]
Probably better off in spring-cloud-kubernetes issues if you're using that project or spring-cloud-netflix if not.

**Comment by vishvarodrigo** [comment]
Change the preferIpAddress value to true. Unlikely other environments k8s pods are not able to find the containers with the hostname. 

```
eureka:
  instance:
    preferIpAddress: true
```

**Comment by markhingston** [comment]
Yep, preferIpAddress param was the problem. Thanks @vishvarodrigo !
