### ISSUE TITLE
Mistake in RoundRobinRule, i'm right?

### ISSUE THREAD

**Issue by Ilnikride** [Netflix/ribbon#466]
Hi!
I suppose the error in
https://github.com/Netflix/ribbon/blob/8b00efdcdad25e319cdb7d1dadfef6464fe4e6c3/ribbon-loadbalancer/src/main/java/com/netflix/loadbalancer/RoundRobinRule.java#L71.

The load will not be balanced even if the server goes down. Might it be better to use reachableServers??

**Comment by mattnelson** [comment]
See also #372

**Comment by Ilnikride** [comment]
Will this behavior be fixed?
